# Generated by Django 5.0.3 on 2024-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
