# Generated by Django 5.0.3 on 2024-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_produto_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
