# Generated by Django 5.0.3 on 2024-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='doutor',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
