# Generated by Django 5.0.3 on 2024-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_alter_doutor_id_alter_paciente_id_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doutor',
            name='especialidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
