# Generated by Django 5.0.3 on 2024-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
