# Generated by Django 5.0.3 on 2024-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_alter_consulta_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='doutor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
