# Generated by Django 5.0.3 on 2024-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_consulta_doutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, choices=[('Farmaco', 'Farmaco'), ('Instrumento', 'Instrumento')], max_length=11, null=True)),
                ('expiration', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Patient',
        ),
        migrations.DeleteModel(
            name='Doutor',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doutor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='data_nascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nome',
            new_name='name',
        ),
    ]
